---
- name: Setup Tomcat
  hosts: all
  become: yes

  tasks:

    - name: Download Tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-11/v11.0.18/bin/apache-tomcat-11.0.18.tar.gz
        dest: /root/apache-tomcat-11.0.18.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /root/apache-tomcat-11.0.18.tar.gz
        dest: /root/
        remote_src: yes

    - name: Rename Tomcat Directory
      command: mv /root/apache-tomcat-11.0.18 /root/tomcat
      args:
        creates: /root/tomcat

    - name: Install Java (OpenJDK 17)
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Configure tomcat-users.xml
      template:
        src: tomcat-users.xml
        dest: /root/tomcat/conf/tomcat-users.xml

    - name: Configure context.xml
      template:
        src: context.xml
        dest: /root/tomcat/webapps/manager/META-INF/context.xml

    - name: Create Tomcat systemd Service File
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Server
          After=network.target

          [Service]
          Type=forking
          User=root
          Group=root
          Environment="JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto.x86_64"
          Environment="CATALINA_HOME=/root/tomcat"
          ExecStart=/root/tomcat/bin/startup.sh
          ExecStop=/root/tomcat/bin/shutdown.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start and Enable Tomcat
      service:
        name: tomcat
        state: started
        enabled: yes


    - name: Copy WAR file to Tomcat
      copy:
        src: /var/lib/jenkins/workspace/NEXUS-CICD/target/myapp.war
        dest: /root/tomcat/webapps/
